### ISSUE TITLE
Is this intended be to something of an easy to setup IoC / dependancy injection type framework?

### ISSUE THREAD

**Issue by MostHated** [sigtrapgames/SmartData#1]
Hey there,
    I was just looking this over and thought it seemed like a neat concept. Is the overall general idea to be a type of IoC / dependency injection framework? I am about to download it to try it out. 

Thanks, 
-MH

**Comment by sigtrapgames** [comment]
Essentially yes. It works a lot like an editor- and data-driven IoC system. If you haven't watched the video at the top of the readme I'd recommend doing so - Ryan mentions DI/IoC there.
