### ISSUE TITLE
[BUG] Dispatch from editor at runtime

### ISSUE THREAD

**Issue by Draudastic** [sigtrapgames/SmartData#3]
![grafik](https://user-images.githubusercontent.com/9055442/45804343-20810500-bcbc-11e8-876a-37a8d4153714.png)

The dispatch button does not trigger the event from code listener. Do I miss something? Or is it a bug?

**Comment by sigtrapgames** [comment]
Seems to be broken yeah. I'll look into it ASAP - thanks for reporting!

**Comment by sigtrapgames** [comment]
Fixed!
